spring:
  application:
    name: quality
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
report:
  directory: /tmp/reports
logging:
  level:
   org.springframework.security: DEBUG
